spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # TODO: 실제 운영 PostgreSQL host:port/db, 계정으로 교체
    url: jdbc:postgresql://prod-db-host:5432/precheck
    username: precheck
    password: precheck
precheck:
  analyze:
    schedule-file-path: /home/precheck/cfg/PreCheck_AnalyzeLogs_Schedule.conf
    policy-file-path: /home/precheck/cfg/PreCheck_AnalyzePolicy.conf